### ISSUE TITLE
Primm's algorithm and PrioirtyQueue test reference methods that don't exist

### ISSUE THREAD

**Issue by YeeP79** [trekhleb/javascript-algorithms#251]
I am guessing there is a new version of PrioirtyQueue that maybe did not get pushed?  Both of the programs in the subject reference PrioirtyQueue.poll() and PrioirtyQueue.isEmpty(), but I do not see them in the data structure. Any help solving this would be much appreciated, your data structures are awesome!

**Comment by YeeP79** [comment]
@trekhleb I see what you are saying, my apologies. I guess my real problem is, the test for MinHeap all pass. However, when I run the Prioirty Queue tests, they all fail when using the peek and poll functions in Heap.
`  PriorityQueue
    ✓ should create default priority queue (4ms)
    ✕ should insert items to the queue and respect priorities (66ms)
    ✕ should poll from queue with respect to priorities (15ms)
    ✕ should be possible to change priority of internal nodes (10ms)
    ✕ should be possible to change priority of head node (9ms)
    ✕ should be possible to change priority along with node addition (8ms)
    ✓ should be possible to search in priority queue by value (4ms)

  ● PriorityQueue › should insert items to the queue and respect priorities

    expect(received).toBe(expected) // Object.is equality

    Expected: 10
    Received: 5

      16 |
      17 |     priorityQueue.add(5, 2);
    > 18 |     expect(priorityQueue.peek()).toBe(10);
         |                                  ^
      19 |
      20 |     priorityQueue.add(100, 0);
      21 |     expect(priorityQueue.peek()).toBe(100);

      at Object.toBe (src/dataStructures/test/PriorityQueue.test.js:18:34)

  ● PriorityQueue › should poll from queue with respect to priorities

    expect(received).toBe(expected) // Object.is equality

    Expected: 100
    Received: 5

      30 |     priorityQueue.add(200, 0);
      31 |
    > 32 |     expect(priorityQueue.poll()).toBe(100);
         |                                  ^
      33 |     expect(priorityQueue.poll()).toBe(200);
      34 |     expect(priorityQueue.poll()).toBe(10);
      35 |     expect(priorityQueue.poll()).toBe(5);

      at Object.toBe (src/dataStructures/test/PriorityQueue.test.js:32:34)

  ● PriorityQueue › should be possible to change priority of internal nodes

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 5

      47 |     priorityQueue.changePriority(10, 20);
      48 |
    > 49 |     expect(priorityQueue.poll()).toBe(200);
         |                                  ^
      50 |     expect(priorityQueue.poll()).toBe(5);
      51 |     expect(priorityQueue.poll()).toBe(100);
      52 |     expect(priorityQueue.poll()).toBe(10);

      at Object.toBe (src/dataStructures/test/PriorityQueue.test.js:49:34)

  ● PriorityQueue › should be possible to change priority of head node

    expect(received).toBe(expected) // Object.is equality

    Expected: 100
    Received: 5

      64 |     priorityQueue.changePriority(10, 20);
      65 |
    > 66 |     expect(priorityQueue.poll()).toBe(100);
         |                                  ^
      67 |     expect(priorityQueue.poll()).toBe(5);
      68 |     expect(priorityQueue.poll()).toBe(200);
      69 |     expect(priorityQueue.poll()).toBe(10);

      at Object.toBe (src/dataStructures/test/PriorityQueue.test.js:66:34)

  ● PriorityQueue › should be possible to change priority along with node addition

    expect(received).toBe(expected) // Object.is equality

    Expected: 100
    Received: 5

      83 |     priorityQueue.add(15, 15);
      84 |
    > 85 |     expect(priorityQueue.poll()).toBe(100);
         |                                  ^
      86 |     expect(priorityQueue.poll()).toBe(5);
      87 |     expect(priorityQueue.poll()).toBe(200);
      88 |     expect(priorityQueue.poll()).toBe(15);

      at Object.toBe (src/dataStructures/test/PriorityQueue.test.js:85:34)`

**Comment by YeeP79** [comment]
I believe this is happening because the heap itself does not have the priority defined by the prioirty queue. In the Heapify Up, it is looking at the values given which in this case:
```
    priorityQueue.add(10, 1);
    expect(priorityQueue.peek()).toBe(10);

    priorityQueue.add(5, 2);
    expect(priorityQueue.peek()).toBe(10);
```
Would be 10, then 5. It puts them in order and the 5 is at the zeroth index. That is incorrect because the 10 has a higher prioirty. 
```
PrioirtyQueue.add:
  add(item, priority = 0) {
    this.priorities[item] = priority
    super.add(item)

    return this
  }
```
I don't see how Heap.peek() would ever get a value with a higher priority when used in conjunction with PrioirtyQueue.add()
