### ISSUE TITLE
Add fibonacci search algorithm

### ISSUE THREAD

**Issue by GharbiSlim** [trekhleb/javascript-algorithms#346]
I wanted to add the Fibonacci search algorithm. I have implemented the algorithm, and the test file. I run also the command npm run lint (successful) . Now when running the command run test I got this error and I could not find a solution:  

● Test suite failed to run
  Your test suite must contain at least one test.

      at node_modules/@jest/core/build/TestScheduler.js:243:24
      at asyncGeneratorStep (node_modules/@jest/core/build/TestScheduler.js:131:24)
      at _next (node_modules/@jest/core/build/TestScheduler.js:151:9)
      at node_modules/@jest/core/build/TestScheduler.js:156:7
      at node_modules/@jest/core/build/TestScheduler.js:148:12
      at onResult (node_modules/@jest/core/build/TestScheduler.js:272:

I need help please

**Comment by GharbiSlim** [comment]
I have solved it. I have missed one line of code 
  it('should search number in sorted array', () => {

**Comment by mik-laj** [comment]
Should we close this issues? Do you still have any problems?
