### ISSUE TITLE
Error: node-canvas was built without JPEG support

### ISSUE THREAD

**Issue by cc4393c** [trekhleb/javascript-algorithms#757]
This error occurd when I was running the file
> src/algorithms/image-processing/seam-carving/__tests__/resizeImageWidth.test.js

```
at Object.<anonymous> (~/javascript-algorithms-master/src/algorithms/image-processing/seam-carving/__tests__/resizeImageWidth.test.js:45:7)
```

```javascript

describe('resizeImageWidth', () => {
  it('should perform content-aware image width reduction', () => {
    // @see: https://jestjs.io/docs/asynchronous
    return Promise.all([
      loadImage(testImageBeforePath), // ERROR at this line !!!
      loadImage(testImageAfterPath),
    ]).then(([imgBefore, imgAfter]) => {
      // Original image.
      // ...
    });
  });
});

```
Do I need to reinstall canvas?

**Comment by bauer23** [comment]
> This error occurd when I was running the file
> 
> > src/algorithms/image-processing/seam-carving/**tests**/resizeImageWidth.test.js
> 
> ```
> at Object.<anonymous> (~/javascript-algorithms-master/src/algorithms/image-processing/seam-carving/__tests__/resizeImageWidth.test.js:45:7)
> ```
> 
>  ```js
> describe('resizeImageWidth', () => {
>   it('should perform content-aware image width reduction', () => {
>     // @see: https://jestjs.io/docs/asynchronous
>     return Promise.all([
>       loadImage(testImageBeforePath), // ERROR at this line !!!
>       loadImage(testImageAfterPath),
>     ]).then(([imgBefore, imgAfter]) => {
>       // Original image.
>       // ...
>     });
>   });
> });
> ```
> 
> Do I need to reinstall canvas?

**Comment by bauer23** [comment]
[at Object.<anonymous> (~/javascript-algorithms-master/src/algorithms/image-processing/seam-carving/__tests__/resizeImageWidth.test.js:45:7)](at Object.<anonymous> (~/javascript-algorithms-master/src/algorithms/image-processing/seam-carving/__tests__/resizeImageWidth.test.js:45:7)) []() 

>

**Comment by bauer23** [comment]
[2021_09_17_18_53_20_ec2_global_view.csv](https://github.com/trekhleb/javascript-algorithms/files/7189033/2021_09_17_18_53_20_ec2_global_view.csv)

**Comment by bauer23** [comment]
https://github.com/bauer23

**Comment by bauer23** [comment]
https://phab.wmfusercontent.org/file/data/v4m4snwhrqph6evr5iyk/PHID-FILE-4v6hphppqx4i47xphbi4/gitlab_login_error
